source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Host', :exclusive => true do

end

target 'Tests', :exclusive => true do
  pod "ZSWHierarchicalResultsController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
