source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZSWHierarchicalResultsController_Example', :exclusive => true do
  pod "ZSWHierarchicalResultsController", :path => "../"
end

target 'ZSWHierarchicalResultsController_Tests', :exclusive => true do
  pod "ZSWHierarchicalResultsController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
