source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Tests_Example', :exclusive => true do
  pod "ZSWHierarchicalResultsController", :path => "../"
end

target 'Tests_Tests', :exclusive => true do
  pod "ZSWHierarchicalResultsController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
